config/routes.rb
RedmineApp::Application.routes.draw do
  get 'members/:id/edit_accessible_repositories',
    :controller  => 'members',
    :action      => 'edit_accessible_repositories',
    :constraints => {:id => /\d+/, :format => /[^.]+/},
    :as          => "edit_member_accessible_repositories"
  put 'members/:id/update_accessible_repositories',
    :controller  => 'members',
    :action      => 'update_accessible_repositories',
    :constraints => {:id => /\d+/, :format => /[^.]+/},
    :as          => "update_member_accessible_repositories"
  get 'repositories/:id/edit_accessible_members',
    :controller  => 'repositories',
    :action      => 'edit_accessible_members',
    :constraints => {:id => /\d+/, :format => /[^.]+/},
    :as          => "edit_repository_accessible_members"
  put 'repositories/:id/update_accessible_members',
    :controller  => 'repositories',
    :action      => 'update_accessible_members',
    :constraints => {:id => /\d+/, :format => /[^.]+/},
    :as          => "update_repository_accessible_members"
end

app/models/member_accessible_repository.rb
class MemberAccessibleRepository < ActiveRecord::Base
  belongs_to :member
  belongs_to :repository

  validates :member_id, uniqueness: { scope: :repository_id}
end

app/views/members/_edit_accessible_repositories.html.erb
<script>
  <%= render partial: 'set_selectallcheckbox' %>
</script>
<%= form_for(@member, :url => update_member_accessible_repositories_path(@member),
                      :as => :membership,
                      :remote => request.xhr?,
                      :method => :put) do |f| %>
  <p>
    <%= check_box_tag(nil, nil, false,
                      :id => "member-#{@member.id}-selectAllMembershipRepositoryIds",
                      :disabled => false) %>
    <label for="checkbox">
      <%= l(:label_select_all) %>
    </label>
    <% @project.repositories.sort.each do |repository| %>
    <label class="block">
      <%= check_box_tag("member-#{@member.id}-membership[repository_ids][]",
                        repository.id, (MemberAccessibleRepository.where(:member_id => @member.id).pluck(:repository_id).include? repository.id),
                        :id => nil,
                        :disabled => false) %> <%= repository.identifier %>
    </label>
    <% end %>
  </p>
  <%= hidden_field_tag "member-#{@member.id}-membership[repository_ids][]", '', :id => nil %>

  <p>
    <%= submit_tag l(:button_save) %>
    <%= link_to_function l(:button_cancel),
                         "$('#member-#{@member.id}-accessible-repositories').show(); $('#member-#{@member.id}-accessible-repositories-form').empty(); return false;" if request.xhr? %>
  </p>
<% end %>

app/views/members/_set_selectallcheckbox.js.erb
$( document ).ready( function() {
  $( "#member-<%= @member.id %>-selectAllMembershipRepositoryIds" ).selectAllCheckbox( {
       checkboxesName   : "member-<%= @member.id %>-membership[repository_ids][]",
       onChangeCallback : function( changedBoxes, status ) {
         checkbox_label = $('div#member-<%= @member.id %>-accessible-repositories-form > form > p:eq(0) > label[for="checkbox"]');
         var GROUP_STATE_NONE = "none",
             GROUP_STATE_SOME = "some",
             GROUP_STATE_ALL  = "all";
         if( status === GROUP_STATE_SOME ) {
           checkbox_label.text("<%= l(:label_select_all) %>");
         } else if( status === GROUP_STATE_ALL ) {
           checkbox_label.text("<%= l(:label_unselect_all) %>");
         } else if( status === GROUP_STATE_NONE ) {
           checkbox_label.text("<%= l(:label_select_all) %>");
         }
       }
    } );
 } );

app/views/members/edit_accessible_repositories.js.erb
$("#member-<%= @member.id %>-accessible-repositories").hide();
$("#member-<%= @member.id %>-accessible-repositories-form").html("<%= escape_javascript(render :partial => "edit_accessible_repositories") %>");

app/views/projects/settings.html.erb
<h2><%=l(:label_settings)%></h2>

<% content_for :header_tags do %>
  <%= javascript_include_tag 'jquery_selectallcheckbox.js', plugin: 'redmine_repository_permission_control' %>
<% end %>

<%= render_tabs project_settings_tabs %>

<% html_title(l(:label_settings)) -%>

app/views/projects/settings/_repositories.html.erb
<% if User.current.allowed_to?(:manage_repository, @project) %>
  <p><%= link_to l(:label_repository_new), new_project_repository_path(@project), :class => 'icon icon-add' %></p>
<% end %>

<% if @project.repositories.any? %>
<div class="autoscroll">
  <table class="list">
    <thead>
      <tr>
        <th><%= l(:field_identifier) %></th>
        <th><%= l(:field_repository_is_default) %></th>
        <th><%= l(:label_scm) %></th>
        <th><%= l(:label_repository) %></th>
        <th></th>
        <th><%= l(:label_accessible_members) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @project.repositories.sort.each do |repository| %>
      <tr id="repository-<%=repository.id %>" class="repository">
        <td class="name">
        <%= link_to repository.identifier,
              {:controller => 'repositories', :action => 'show',:id => @project, :repository_id => repository.identifier_param} if repository.identifier.present? %>
        </td>
        <td><%= checked_image repository.is_default? %></td>
        <td><%= repository.scm_name %></td>
        <td><%= repository.url %></td>
        <td class="buttons">
        <% if User.current.allowed_to?(:manage_repository, @project) %>
          <%= link_to(l(:label_user_plural), committers_repository_path(repository),
               :class => 'icon icon-user') %>
          <%= link_to(l(:button_edit), edit_repository_path(repository),
               :class => 'icon icon-edit') %>
          <%= delete_link repository_path(repository) %>
        <% end %>
        </td>
        <% if User.current.allowed_to?(:manage_repository, @project) %>
          <td class="accessible-members">
            <span id="repository-<%=repository.id %>-accessible-members"><%= Member.find(repository.accessible_member_ids).map(&:user).compact.pluck(:firstname).sort.collect(&:to_s).join(', ') %></span>
            <div id="repository-<%=repository.id %>-accessible-members-form"></div>
          </td>
          <td class="buttons">
              <%= link_to l(:button_edit_permission),
                          edit_repository_accessible_members_path(repository),
                          :remote => true,
                          :class => 'icon icon-edit' %>
          </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/repositories/_edit_accessible_members.html.erb
<script>
  <%= render partial: 'set_selectallcheckbox' %>
</script>
<%= form_for(@repository, :url => update_repository_accessible_members_path(@repository),
                      :as => :membership,
                      :remote => request.xhr?,
                      :method => :put) do |f| %>
  <p>
    <%= check_box_tag(nil, nil, false,
                      :id => "repository-#{@repository.id}-selectAllMembershipRepositoryIds",
                      :disabled => false) %>
    <label for="checkbox">
      <%= l(:label_select_all) %>
    </label>
    <% @project.members.sort.each do |member| %>
    <label class="block">
      <%= check_box_tag("repository-#{@repository.id}-membership[member_ids][]",
                        member.id, (MemberAccessibleRepository.where(:repository_id => @repository.id).pluck(:member_id).include? member.id),
                        :id => nil,
                        :disabled => false) %> <%= member.user.firstname %>
    </label>
    <% end %>
  </p>
  <%= hidden_field_tag "repository-#{@repository.id}-membership[member_ids][]", '', :id => nil %>

  <p>
    <%= submit_tag l(:button_save) %>
    <%= link_to_function l(:button_cancel),
                         "$('#repository-#{@repository.id}-accessible-members').show(); $('#repository-#{@repository.id}-accessible-members-form').empty(); return false;" if request.xhr? %>
  </p>
<% end %>

app/views/repositories/_set_selectallcheckbox.js.erb
$( document ).ready( function() {
  $( "#repository-<%= @repository.id %>-selectAllMembershipRepositoryIds" ).selectAllCheckbox( {
       checkboxesName   : "repository-<%= @repository.id %>-membership[member_ids][]",
       onChangeCallback : function( changedBoxes, status ) {
         checkbox_label = $('div#repository-<%= @repository.id %>-accessible-members-form > form > p:eq(0) > label[for="checkbox"]');
         var GROUP_STATE_NONE = "none",
             GROUP_STATE_SOME = "some",
             GROUP_STATE_ALL  = "all";
         if( status === GROUP_STATE_SOME ) {
           checkbox_label.text("<%= l(:label_select_all) %>");
         } else if( status === GROUP_STATE_ALL ) {
           checkbox_label.text("<%= l(:label_unselect_all) %>");
         } else if( status === GROUP_STATE_NONE ) {
           checkbox_label.text("<%= l(:label_select_all) %>");
         }
       }
    } );
 } );

app/views/repositories/edit_accessible_members.js.erb
$("#repository-<%= @repository.id %>-accessible-members").hide();
$("#repository-<%= @repository.id %>-accessible-members-form").html("<%= escape_javascript(render :partial => "edit_accessible_members") %>");

app/views/repositories/update_accessible_members.js.erb
$('#tab-content-repositories').html('<%= escape_javascript(render :partial => 'projects/settings/repositories') %>');
hideOnLoad();
$("#repository-<%= @repository.id %>").effect("highlight");

app/views/settings/_accessible_repositories_table_header.html.erb
<th><%= l(:label_accessible_repositories) %></th>
<th></th>

app/views/settings/_accessible_repositories_table_row.html.erb
<td class="accessible-repositories">
  <span id="member-<%= member.id %>-accessible-repositories"><%= Repository.find(member.accessible_repository_ids).pluck(:identifier).sort.collect(&:to_s).join(', ') %></span>
  <div id="member-<%= member.id %>-accessible-repositories-form"></div>
</td>
<td class="buttons">
    <%= link_to l(:button_edit_permission),
                edit_member_accessible_repositories_path(member),
                :remote => true,
                :class => 'icon icon-edit' %>
</td>

app/views/settings/_inaccessible_repositories_table_header.html.erb
<th><%= l(:label_accessible_repositories) %></th>
<th></th>

app/views/settings/_inaccessible_repositories_table_row.html.erb
<td class="accessible-repositories">
  <span id="member-<%= member.id %>-accessible-repositories"><%= (@project.repositories.pluck(:identifier) - Repository.find(member.inaccessible_repository_ids).pluck(:identifier)).sort.collect(&:to_s).join(', ') %></span>
  <div id="member-<%= member.id %>-accessible-repositories-form"></div>
</td>
<td class="buttons">
    <%= link_to l(:button_edit),
                edit_member_accessible_repositories_path(member),
                :remote => true,
                :class => 'icon icon-edit' %>
</td>